base/urls.py
from django.urls import path

from base import views, ajax

app_name = 'base'
urlpatterns = [
    path('', views.home, name='home'),
    path('articles/<int:id>/', views.detail_info, name="detail"),
    path('result/filter/', ajax.filter_result, name='result-filter'),
]

core_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.views import serve as serve_static
from django.urls import include, path, re_path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


def _static_butler(request, path, **kwargs):
    """
    Serve static files using the django static files configuration
    WITHOUT collectstatic. This is slower, but very useful for API
    only servers where the static files are really just for /admin

    Passing insecure=True allows serve_static to process, and ignores
    the DEBUG=False setting

    source: https://stackoverflow.com/a/57179415/5136746
    """
    return serve_static(request, path, insecure=True, **kwargs)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls', namespace='base')),
]

urlpatterns += staticfiles_urlpatterns()  # Add directory https://stackoverflow.com/a/12801140

if settings.DEBUG is False:  # if DEBUG is True it will be served automatically
    urlpatterns += [re_path(r'static/(.+)', _static_butler)]

base/views.py
import csv

import requests
from django.shortcuts import render

from .models import Element, Source, Repositorie, Author, Topic
from base.exercise import get_vars

API_KEY = "ocmhB4lIsNdQW7TVZyXLOPkUn8bFEupv"


def create_file(sources):
    """

    :param sources: Articulos
    :return:
    """
    with open('static/data.csv', mode='w', encoding='utf-8') as csv_file:
        fieldnames = ['title', 'authors', 'groups', 'keywords', 'topics', 'abstract']
        writer = csv.DictWriter(csv_file, fieldnames=fieldnames)

        writer.writeheader()
        for source in sources:
            topics = ", ".join([record.name for record in source.topics_m2m.all()])
            groups = ", ".join([record.name for record in source.repositories_m2m.all()])
            authors = ", ".join([record.name for record in source.authors_m2m.all()])
            if isinstance(source, Source):
                writer.writerow({
                    'title': source.title,
                    'authors': authors,
                    'groups': groups,
                    'keywords': topics,
                    'topics': topics,
                    'abstract': source.description,
                })


# Create your views here.
def home(request):
    # id de los objeto Source
    source_ids = []
    page_number = int(request.GET.get('page', 1))
    page_has_previous, page_has_next = False, False
    totalHits = 0
    num_pages = 0
    query = request.GET.get('q', '')
    if query:
        page_has_previous = page_number > 1
        URL = "https://core.ac.uk:443/api-v2/search/%s" % query
        pageSize = 10
        payload = {
            'page': page_number,
            'pageSize': pageSize,
            'apiKey': API_KEY,
        }
        try:
            r = requests.get(url=URL, params=payload)

            response = r.json()

            if 'totalHits' in response:
                totalHits = response['totalHits']
                num_pages = totalHits / pageSize
                if (pageSize * page_number) < totalHits:
                    num_pages += 1
                page_has_next = totalHits > (pageSize * page_number)

            if 'data' in response:
                data = response['data']
                for record in data:
                    if '_id' in record:
                        _id = record['_id']
                        fields_element = {
                            '_score': record['_score']
                        }
                        if '_index' in record:
                            fields_element['_index'] = record['_index']
                        if '_type' in record:
                            fields_element['_type'] = record['_type']
                        elements = Element.objects.filter(_id=_id)
                        # Select * from tabla where _id=5; Element.objects.filter(_id=5)
                        # Select * from tabla; = Element.objects.all()

                        if elements.exists():
                            elements.update(**fields_element)
                            element = elements.first()
                        else:
                            fields_element['_id'] = _id
                            element = Element.objects.create(**fields_element)  # SQL insert

                        if isinstance(element, Element):
                            if '_source' in record:
                                _source = record['_source']
                                if 'id' in _source:
                                    source_id = _source['id']
                                    source_ids.append(source_id)
                                    kwargs_source = {}
                                    for key, value in _source.items():
                                        """Verifico si el atributo key existe en la clase Source"""
                                        if hasattr(Source, key):
                                            kwargs_source[key] = value

                                    sources = element.source_set.filter(id=source_id)
                                    if sources.exists():
                                        element.source_set.update(**kwargs_source)
                                        source = sources.first()
                                    else:
                                        source = Source.objects.create(element=element, **kwargs_source)

                                    if 'repositories' in _source:
                                        fields_repositorie = {}
                                        repositories = _source['repositories']

                                        for repository in repositories:
                                            for key, value in repository.items():
                                                if hasattr(Repositorie, key):
                                                    fields_repositorie[key] = value

                                            repositories = Repositorie.objects.filter(id=repository['id'])

                                            if repositories.exists():
                                                repositorie = Repositorie.objects.get(id=repository['id'])
                                            else:
                                                # Si repositorio no existe lo creo
                                                repositorie = Repositorie.objects.create(**fields_repositorie)

                                            # Añadir los repositorios al articulo
                                            source.repositories_m2m.add(repositorie)

                                    if 'authors' in _source:
                                        authors = _source['authors']

                                        for name_author in authors:
                                            author, created = Author.objects.get_or_create(name=name_author)
                                            # Añado al autor actual
                                            source.authors_m2m.add(author)

                                    if 'topics' in _source:
                                        topics = _source['topics']

                                        for topic in topics:
                                            obj, created = Topic.objects.get_or_create(name=topic)
                                            source.topics_m2m.add(obj)
        except ConnectionError as e:
            # Cuando hay un error en la conexión
            pass
        except TimeoutError as e:
            pass
        except Exception as e:
            return article_search(request)

        sources = Source.objects.filter(id__in=source_ids)
        create_file(sources)
        my_data = get_vars()
        return render(request, 'base/result.html', context={
            'query': query,
            'sources': sources,
            'totalHits': totalHits,
            'page_number': page_number,
            'num_pages': num_pages,
            'page_has_previous': page_has_previous,
            'page_has_next': page_has_next,
            'my_data': my_data,
        })
    return render(request, 'base/index.html')


def article_search(request):
    # id de los objeto Source
    source_ids = []

    query = request.GET.get('q', '')
    if query:
        URL = "https://core.ac.uk:443/api-v2/articles/search/%s" % query
        payload = {
            'page': 1,
            'pageSize': 10,
            'metadata': True,
            'fulltext': False,
            'citations': False,
            'similar': True,
            'duplicate': False,
            'urls': False,
            'faithfulMetadata': False,
            'apiKey': API_KEY,
        }
        try:
            r = requests.get(url=URL, params=payload)

            response = r.json()
            if 'status' in response:
                pass

            if 'totalHits' in response:
                totalHits = response['totalHits']

            if 'data' in response:
                data = response['data']
                for _source in data:
                    if 'id' in _source:
                        source_id = _source['id']
                        source_ids.append(source_id)
                        kwargs_source = {}
                        for key, value in _source.items():
                            """Verifico si el atributo key existe en la clase Source"""
                            if hasattr(Source, key):
                                kwargs_source[key] = value

                        sources = Source.objects.filter(id=source_id)
                        if sources.exists():
                            sources.update(**kwargs_source)
                            source = sources.first()
                        else:
                            source = Source.objects.create(**kwargs_source)

                        if 'repositories' in _source:
                            fields_repositorie = {}
                            repositories = _source['repositories']

                            for repository in repositories:
                                for key, value in repository.items():
                                    if hasattr(Repositorie, key):
                                        fields_repositorie[key] = value

                                repositories = Repositorie.objects.filter(id=repository['id'])

                                if repositories.exists():
                                    repositorie = Repositorie.objects.get(id=repository['id'])
                                else:
                                    # Si repositorio no existe lo creo
                                    repositorie = Repositorie.objects.create(**fields_repositorie)

                                source.repositories_m2m.add(repositorie)

                        if 'authors' in _source:
                            authors = _source['authors']

templates/base/detail_view.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
{# tomado de https://getbootstrap.com/docs/4.0/examples/checkout/ #}
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" type="image/png" href="{% static 'base/img/inteligencia-artificial.png' %}"/>
  <link rel="icon" type="image/svg" href="https://www.flaticon.es/svg/static/icons/svg/1122/1122567.svg"/>

  <title>Landing Page - Start Bootstrap Theme</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'base/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="{% static 'base/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
  <link href="{% static 'base/vendor/simple-line-icons/css/simple-line-icons.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet"
        type="text/css">

  <!-- Custom styles for this template -->
  <link href="{% static 'base/' %}css/landing-page.min.css" rel="stylesheet">

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-light bg-light static-top">
  <div class="container">
    <a class="navbar-brand" href="{% url 'base:home' %}">{% trans 'Home' %}</a>
  </div>
</nav>

<!-- Masthead -->

<div class="container">
  <div class="card mb-3">
    <div class="card-header">{{ source.title }}</div>
    <div class="row g-3">
      <div class="col-md-4">
        <img src="https://core.ac.uk/image/{{ source.id }}/large" id="preview_image" alt="Article thumbnail">
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h2 class="card-title" style="font-weight: bold;">{{ source.title}}</h2>
          <p>
            <strong>Autor:</strong> {% for author in source.authors_m2m.all %}{{ author }}{% endfor %}
          </p>
          <h4>Abstract</h4>
          <p class="card-text text-justify">{{ source.description|default_if_none:"" }}</p>
          <strong>Repositorio:
            {% for repository in source.repositories_m2m.all %}
              <a href="{% url 'base:home' %}?q=repositories.id:({{ repository.pk }})">{{ repository }}</a>
            {% endfor %}
            <p>
              <strong>Topics: </strong> <span class="text-dark">{{ source.topics_m2m.all|join:", " }}</span>
            </p>
          <p>
            <strong>Año: </strong>{{ source.year }}<br>
            {% if source.doi %}<strong class="text-uppercase">doi: </strong>{{ source.doi|default_if_none:"" }}<br>{% endif %}
            {% if source.oai %}<strong class="text-uppercase">oai: </strong>{{ source.oai|default_if_none:"" }}<br>{% endif %}
            {% if source.fullTextIdentifier %}<strong>Descargado desde</strong><br>
            <a href="{{ source.fullTextIdentifier }}" target="_blank">{{ source.fullTextIdentifier }}</a>{% endif %}
          </p>
          <p class="card-text"><small class="text-muted">Actualizado hace {{ source.write_date|timesince }}</small></p>
          </strong>
        </div>
        <div class="card-body">
          {% if source.downloadUrl %}<a href="{{ source.downloadUrl }}" class="btn btn-outline-primary"> <i class="fa fa-1x fa-download"></i> Descargar</a>{% endif %}
        </div>
      </div>
    </div>
  </div>
  <h2 class="blog-post-title">Artículos similares</h2>
  <div class="row">
    {% for record in sources %}
    <div class="col-md-12">
      <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <a href="{% url 'base:home' %}?q=repositories.id:({{ record.repositoryId }})" class="text-success">{{ record.repositoryName }}</a>
          <h3 class="mb-0">
            <a class="text-primary" href="{% url 'base:detail' record.pk %}" id="title" title="{{ record.title }}">{{ record.title|truncatewords:10 }}</a>
          </h3>
          <div class="mb-1 text-muted"><strong>Por:</strong> {% for author in source.authors_m2m.all %}{{ author }}{% endfor %}</div>
          {% if record.year %}<div class="mb-1 text-muted">{{ record.year }}</div>{% endif %}
          {% if record.publisher %}<p class="mb-auto"><strong>Editor: </strong>{{ record.publisher }}</p>{% endif %}
        </div>
        <div class="col-auto d-none d-lg-block">
          <img class="card-img-right flex-auto d-none d-md-block" data-src="holder.js/200x250?theme=thumb" alt="Thumbnail [200x250]" style="width: 200px; height: 250px;" src="https://core.ac.uk/image/{{ record.id }}/medium" data-holder-rendered="true">
        </div>
      </div>
    </div>{% endfor %}
  </div>
</div>
</body>
</html>

templates/base/result.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
{# tomado de https://getbootstrap.com/docs/4.0/examples/checkout/ #}
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" type="image/png" href="{% static 'base/img/inteligencia-artificial.png' %}"/>
  <link rel="icon" type="image/svg" href="https://www.flaticon.es/svg/static/icons/svg/1122/1122567.svg"/>

  <title>Landing Page - Start Bootstrap Theme</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'base/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="{% static 'base/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
  <link href="{% static 'base/vendor/simple-line-icons/css/simple-line-icons.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet"
        type="text/css">

  <!-- Custom styles for this template -->
  <link href="{% static 'base/css/landing-page.min.css' %}" rel="stylesheet">

  <style>
    body {
      font-family: Arial, Helvetica, sans-serif;
    }

    /* The Modal (background) */
    .modal {
      display: none; /* Hidden by default */
      position: fixed; /* Stay in place */
      z-index: 1; /* Sit on top */
      padding-top: 100px; /* Location of the box */
      left: 0;
      top: 0;
      width: 100%; /* Full width */
      height: 100%; /* Full height */
      overflow: auto; /* Enable scroll if needed */
      background-color: rgb(0, 0, 0); /* Fallback color */
      background-color: rgba(0, 0, 0, 0.4); /* Black w/ opacity */
    }

    /* Modal Content */
    .modal-content {
      background-color: #fefefe;
      margin: auto;
      padding: 20px;
      border: 1px solid #888;
      width: 80%;
    }

    /* The Close Button */
    .close {
      color: #aaaaaa;
      float: right;
      font-size: 28px;
      font-weight: bold;
    }

    .close:hover,
    .close:focus {
      color: #000;
      text-decoration: none;
      cursor: pointer;
    }
  </style>
</head>
<body>

<!-- Navigation -->
<nav class="navbar navbar-light bg-light static-top">
  <div class="container">
    <a class="navbar-brand" href="{% url 'base:home' %}">{% trans 'Home' %}</a>
  </div>
</nav>

<!-- Masthead -->

<div class="container">
  <div class="py-5 text-center">
    <img class="d-block mx-auto mb-4" src="{% static 'base/img/inteligencia-artificial.svg' %}" alt="" width="72" height="72">
    <h2>Buscador</h2>
    <form>
      <div class="form-row">
        <div class="col-12 col-md-9 mb-2 mb-md-0">
          <input type="text" class="form-control form-control-lg" placeholder="Criterio a buscar..." value="{{ query }}" name="q" autocomplete="off">
        </div>
        <div class="col-12 col-md-3">
          <button type="submit" class="btn btn-block btn-lg btn-primary">Buscar!</button>
        </div>
      </div>
    </form>

  </div>
  <div class="row">
    <div class="col-md-12 order-md-2" id="id_div_result">
      <p>
        Mostrando búsqueda para <strong>{{ query}}</strong> ({{ totalHits}} resultados encontrados) <a href="#" id="myBtn">Ver Matrices</a>
      </p>
      {% for source in sources %}
      <div class="card flex-md-row mb-4 box-shadow h-md-250">
        <div class="card-body d-flex flex-column align-items-start">
          <h4 class="mb-0">
            <a class="text-primary" href="{% url 'base:detail' source.pk %}" id="title" title="{{ source.title }}">{{ source.title|truncatewords:10 }}</a>
          </h4>
          <div class="mb-1 text-muted"><strong>Por:</strong> {% for author in source.authors_m2m.all %}{{ author }}{% endfor %}</div>
          <p>
            <strong>Repositorio: </strong> <span class="text-danger" id="repository">{% for repository in source.repositories_m2m.all %}
            <a href="{% url 'base:home' %}?q=repositories.id:({{ repository.pk }})">{{ repository }}</a>
          {% endfor %}</span>
          </p>
          {% if source.description %}<p class="card-text mb-auto">{{ source.description|truncatewords:25 }}</p>{% endif %}
        </div>
        <img class="card-img-right flex-auto d-none d-md-block" data-src="holder.js/200x250?theme=thumb"
             alt="Thumbnail [200x250]" style="width: 200px; height: 250px;"
             src="https://core.ac.uk/image/{{ source.id }}/medium"
             data-holder-rendered="true">
      </div>{% endfor %}
    </div>
  </div>
  <div class="row">
    <nav aria-label="Page navigation example">
      <ul class="pagination justify-content-end">
        <li class="page-item{% if not page_has_previous %} disabled{% endif %}">
          <a class="page-link" href="?q={{ query }}&page={{ page_number|add:-1 }}" tabindex="-1"{% if not page_has_previous %} aria-disabled="true"{% endif %}>Anterior</a>
        </li>
        <li class="page-item active"><a class="page-link">Página {{ page_number }} de {{ num_pages }}.</a></li>
        <li class="page-item{% if not page_has_next %} disabled{% endif %}">
          <a class="page-link" href="?q={{ query }}&page={{ page_number|add:1 }}"{% if not page_has_previous %} aria-disabled="true"{% endif %}>Siguiente</a>
        </li>
      </ul>
    </nav>
  </div>
  <div>

    <!-- The Modal -->
    <div id="myModal" class="modal">

      <!-- Modal content -->
      <div class="modal-content">
        <span class="close">&times;</span>
        <p>
          El archivo fue obtenido desde <a href="/static/data.csv">data.csv</a>
        </p>
        <div class="row">
          <div class="col-md-6">
            {% if my_data.mc %}
              <p>Matriz Coseno</p>
              <div class="table-responsive">
                <table class="table table-striped table-sm">
                  <tbody>
                  {% for row in my_data.mc %}
                    <tr class="small">{% for column in row %}<td>{{ column }}</td>{% endfor %}</tr>
                  {% endfor %}
                  </tbody>
                </table>
              </div>
            {% else %}
              <p>Matrices no enviadas</p>
            {% endif %}
          </div>
          <div class="col-md-6">
            {% if my_data.tf_idf %}
              <p>TD IDF</p>
              <div class="table-responsive">
                <table class="table table-striped table-sm">
                  <tbody>
                  {% for row in my_data.tf_idf %}
                    <tr class="small">{% for column in row %}<td>{{ column }}</td>{% endfor %}</tr>
                  {% endfor %}
                  </tbody>
                </table>
              </div>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>

  <footer class="my-5 pt-5 text-muted text-center text-small">
    <p class="mb-1">© 2017-2018 Company Name</p>
    <ul class="list-inline">
      <li class="list-inline-item"><a href="#">Privacy</a></li>
      <li class="list-inline-item"><a href="#">Terms</a></li>
      <li class="list-inline-item"><a href="#">Support</a></li>
    </ul>
  </footer>
</div>

<!-- Footer -->
<footer class="footer bg-light">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 h-100 text-center text-lg-left my-auto">
        <ul class="list-inline mb-2">
          <li class="list-inline-item">
            <a href="#">About</a>
          </li>
          <li class="list-inline-item">&sdot;</li>
          <li class="list-inline-item">
            <a href="#">Contact</a>
          </li>
          <li class="list-inline-item">&sdot;</li>
          <li class="list-inline-item">
            <a href="#">Terms of Use</a>
          </li>
          <li class="list-inline-item">&sdot;</li>
          <li class="list-inline-item">
            <a href="#">Privacy Policy</a>
          </li>
        </ul>
        <p class="text-muted small mb-4 mb-lg-0">&copy; Your Website 2020. All Rights Reserved.</p>
      </div>
      <div class="col-lg-6 h-100 text-center text-lg-right my-auto">
        <ul class="list-inline mb-0">
          <li class="list-inline-item mr-3">
            <a href="#">
              <i class="fab fa-facebook fa-2x fa-fw"></i>
            </a>
          </li>
          <li class="list-inline-item mr-3">
            <a href="#">
              <i class="fab fa-twitter-square fa-2x fa-fw"></i>
            </a>
          </li>
          <li class="list-inline-item">
            <a href="#">
              <i class="fab fa-instagram fa-2x fa-fw"></i>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        // Get the modal
        var modal = document.getElementById("myModal");

        // Get the button that opens the modal
        var btn = document.getElementById("myBtn");

        // Get the <span> element that closes the modal
        var span = document.getElementsByClassName("close")[0];

        // When the user clicks on the button, open the modal
        btn.onclick = function () {
            modal.style.display = "block";
        }

        // When the user clicks on <span> (x), close the modal
        span.onclick = function () {
            modal.style.display = "none";
        }

        // When the user clicks anywhere outside of the modal, close it
        window.onclick = function (event) {
            if (event.target === modal) {
                modal.style.display = "none";
            }
        }
    });
  </script>
</body>
</html>